# Same thing than the 'server' Dockerfile.
FROM python:latest

# Same thing than the 'server' Dockerfile.
# We import 'client.py' in '/client/' folder.
ADD client.py /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/client/

# I would like to introduce something new, the 'WORKDIR' command.
# This command changes the base directory of your image.
# Here we define '/client/' as base directory.
WORKDIR /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/client/
