version: '3'

services: 
 cas2: 
    container_name: cassan2
    image: cassandra:latest
    volumes:
      - ./../data/cassandra/node1:/var/lib/cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks:
      - assignment
 server:
    container_name: server
    image: python:3.6-stretch
    command: /bin/bash -c "ls"
    volumes:
      - ./server:/var/lib/server
    ports:
      - 9043:9043
    tty: true
    networks:
      - assignment

networks:
  assignment: {}

    
