version: '3'

services: 
 cas2: 
    container_name: cas2
    image: cassandra:latest
    volumes:
      - /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/cassandra/node1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
 server:
    build: /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/server/
    command: python ./server.py
    ports:
      - 1234:1234
 client:
    build: /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
