version: '3'

services: 
 cas1: 
    container_name: cas2
    image: cassandra:latest
    volumes:
      - /home/clement/WKS/AALTO/BigData/assignment-2-784795/data/cassandra/node1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1

